"""Plain entry point for debugging gate_by_gate with PyCharm's normal debugger.

Why this exists: debugging gate_by_gate via the notebook's "Debug Cell" doesn't
bind breakpoints in gate_by_gate.py, because the WSL interpreter's path mappings
in jdk.table.xml are auto-regenerated by PyCharm from a corrupted target config
and never cover thesisNotebooks/. Running this script under a normal Python
run/debug configuration lets you set the local<->WSL path mapping ON THE RUN
CONFIG (which PyCharm preserves), so breakpoints in gate_by_gate.py bind.

Usage:
  - Set breakpoints in gate_by_gate.py (e.g. line 311 = top of the per-gate loop,
    line 374 = detector-mismatch return, line 396 region = perform_had).
  - Right-click this file -> "Debug 'debug_gbg'".
  - In the run config, add Path mappings:
        C:\\Users\\larab\\Desktop\\masters\\Thesis 3\\Thesis
        = /mnt/c/Users/larab/Desktop/masters/Thesis 3/Thesis
"""

import gate_by_gate as gbg
import tsim

# A circuit with detectors so the detector / mismatch breakpoints are reachable.
# Swap in any circuit from test_gbg.py.
circuit = tsim.Circuit(
    """
    RX 0
    R 1
    RX 2
    CX 0 1
    T_DAG 0
    H 1
    CX 2 1 2 0
    MX 2
    RX 2
    CX 2 1 2 0
    MX 2
    DETECTOR rec[-1] rec[-2]
    """
)


def main(num_shots: int = 20) -> None:
    splits, noise_ops = gbg.preprocessing(circuit)
    detects = None
    counts: dict[str, int] = {}
    passed_count = 0
    for _ in range(num_shots):
        passed, result, detects, obs = gbg.gate_by_gate(
            circuit, splits, noise_ops, detects
        )
        if passed:
            passed_count += 1
            key = "".join(map(str, result))
            counts[key] = counts.get(key, 0) + 1
    print(f"passed {passed_count}/{num_shots}")
    for k, v in sorted(counts.items()):
        print(f"  |{k}>: {v}")


if __name__ == "__main__":
    main()
